const responseConstants = {
  SET_RESPONSES: 'SET_RESPONSES',
  VIEW_RESPONSE: 'VIEW_RESPONSE',
  APPROVE_RESPONSE: 'APPROVE_RESPONSE',
  REJECT_RESPONSE: 'REJECT_RESPONSE',
};

module.exports = responseConstants;
